services:
  db:
    container_name: fitness
    image: postgres:latest
    environment:
      POSTGRES_USER: fratzkian
      POSTGRES_PASSWORD: Ki@Npagobo123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:




